package Records;

// released from 14 onwards, currently using 8, thus the error
// record is a special type of class
// the parameters are generated as private and final by default
// getter methods are also generated automatically but without "get" prefix on the method names
// no setter methods
// hashCode and equals methods are automatically generated

//public record EmployeeRecord (String name, int employeeNumber){
//    you can create instance and static methods and fields here
//    not allowed to create non-static instance fields
//    you cannot extend other class (implicitly final classes), but you can implement interface
//    you can define your own constructor by overriding the constructor generated by default
//}
